name: dn42-webrtc-chat
networks:
  dn42-webrtc-chat:
    name: "dn42-webrtc-chat"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: "${DN42_SUBNET}"
          gateway: "${DN42_HOST_GW}"
volumes:
  caddydata:
services:
  web:
    container_name: dn42-webrtc-chat
    image: docker.io/library/caddy:latest
    pull_policy: always
    networks:
      dn42-webrtc-chat:
        ipv6_address: "${DN42_ULA}"
    volumes:
      - "./caddy.json:/caddy.json:ro"
      - "./dn42-root-ca.crt:/dn42-root-ca.crt:ro"
      - "./resolv.conf:/etc/resolv.conf:ro"
      - "caddydata:/caddydata"
    command:
      - "caddy"
      - "run"
      - "--config=/caddy.json"
